const bg=document.getElementById('star-bg');
for(let i=0;i<60;i++){const s=document.createElement('div');s.className='star';const z=Math.random()*3+1;s.style.width=s.style.height=z+'px';s.style.top=Math.random()*100+'vh';s.style.left=Math.random()*100+'vw';s.style.animationDelay=Math.random()*2+'s';bg.appendChild(s)}
function nextScreen(n){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById('s'+n).classList.add('active');if(n===8)startStarGame()}
function moveNoBtn(){const b=document.getElementById('no-btn'),box=document.querySelector('.btn-container');b.style.left=Math.random()*Math.max(0,box.clientWidth-b.offsetWidth)+'px';b.style.top=Math.random()*Math.max(0,box.clientHeight-b.offsetHeight)+'px'}
function checkRewrite(step,target,next){const v=document.getElementById('rw'+step).value.trim(),e=document.getElementById('err'+step);if(v===target){e.innerText='✓ Verified. Proceeding...';setTimeout(()=>nextScreen(next),600)}else e.innerText='Mismatched character matrix. Try again.'}
function wrongQuiz(btn){btn.style.borderColor='#ff4575';btn.style.color='#ff4575';document.getElementById(btn.parentNode.id==='s6'?'quiz-err1':'quiz-err2').innerText='Access Denied. That choice is invalid in my reality.'}
let starScore=0;
function startStarGame(){starScore=0;document.getElementById('star-status').innerText='Score: 0/3';document.getElementById('catcher-zone').innerHTML='';spawnStar()}
function spawnStar(){if(starScore>=3){nextScreen(9);return}const z=document.getElementById('catcher-zone'),s=document.createElement('div'),good=Math.random()>.35;s.className='game-star';s.innerText=good?'⭐ You':'✨ Others';s.style.top=Math.random()*160+10+'px';s.style.left=Math.random()*65+10+'%';s.onclick=()=>{if(good){starScore++;document.getElementById('star-status').innerText=`Score: ${starScore}/3`;s.remove();spawnStar()}else{document.getElementById('star-status').innerText="Wrong focus! Click on 'You'.";s.style.transform='scale(.5)';setTimeout(()=>{if(s.parentNode)s.remove();spawnStar()},400)}};z.appendChild(s)}
function spinWheel(){const b=document.getElementById('spin-btn'),t=document.getElementById('wheel-text'),s=document.getElementById('wheel-status');b.disabled=true;t.innerText='Spinning...';setTimeout(()=>{t.innerText='Treat Promised 🍕';s.innerText='Result locked: Bestie will treat me soon. Proceeding...';setTimeout(()=>nextScreen(10),2500)},2000)}
const comps=['You have an amazing smile, even when you share it elsewhere.','You are incredibly intelligent, though you miss my silent hints.','Your presence holds unmatched value in my quiet life.'];let compIndex=0;
function showCompliment(){if(compIndex<comps.length){document.getElementById('compliment-text').innerText=comps[compIndex++];if(compIndex===comps.length)document.getElementById('comp-btn').innerText='Unlock Final Layer'}else nextScreen(11)}
let cakeCut=false;
function cutCake(){if(cakeCut)return;cakeCut=true;document.getElementById('final-cake').innerText='🍰✨';document.getElementById('cake-instruction').innerText='Happy Birthday, Chagol! 🎉';for(let i=0;i<60;i++){const c=document.createElement('div');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.top='-10px';c.style.animationDelay=Math.random()*2+'s';c.style.background=['#ff758c','#ff4575','#ffeb3b','#bdafcf'][Math.floor(Math.random()*4)];document.body.appendChild(c)}for(let i=0;i<30;i++){const b=document.createElement('div');b.className='balloon';b.innerText=['🎈','🎈','💝','🎂','✨'][Math.floor(Math.random()*5)];b.style.left=Math.random()*100+'vw';b.style.setProperty('--x-move',(Math.random()*240-120)+'px');b.style.animationDelay=Math.random()*1.8+'s';b.style.fontSize=Math.random()*20+25+'px';document.body.appendChild(b)}}
